name: Code Quality

on:
  pull_request:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Set up Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 1.8.3

      - name: Verify Biome Installation
        run: npx biome --version

      - name: Run Biome
        run: npx biome lint .